build: fix merge queue issues (#1654)
Closes #1482 

There are two known issues when attempting to merge PRs via merge queue:

- CodeQL fails with: 
```
Error: ref 'refs/heads/gh-readonly-queue/main/pr-968-499f37f64b27c66d4fc68446dbea519860d06cf7' not found in this repository
```

- CI.changelog fails with: 
```
Get current git ref
Error: The process '/usr/bin/git' failed with exit code [1](https://github.com/Unstructured-IO/unstructured/actions/runs/5735977683/job/15544656682#step:2:1)28
```

The error with CodeQL is a known and still [open
issue](https://github.com/github/codeql-action/issues/1572). We don't
current enforce branch protection for CodeQL, so probably our best
compromise is to simply not run this on the merge queue event. There
could be a narrow margin where some issue is introduced via merge, but
we'll still see issues on individual branches and on pushes to main, so
this is probably acceptable.

The changelog job now has a checkout step prior to paths-filter which
guarantees the git ref exists before attempting to execute the filter
action.

## Testing

Prior to this change, I was able to validate both the
[CodeQL](https://github.com/ryan-nikolaidis/unstructured/actions/runs/6414128010)
and
[changelog](https://github.com/ryan-nikolaidis/unstructured/actions/runs/6414128007/job/17414065768)
test errors

With these changes, validated that the merge queue was able to
[successfully
run](https://github.com/ryan-nikolaidis/unstructured/actions/runs/6414511843/job/17415024319)
the changelog CI job.